CREATE TABLE IF NOT EXISTS relatorio_manutencao (
    id_relatorio_manutencao INT NOT NULL AUTO_INCREMENT,
    id_subestacao INT NOT NULL,
    id_tipo_ativo INT NOT NULL,
    periodicidade VARCHAR(20) NOT NULL,
    data_referencia DATE NOT NULL,
    observacao TEXT NULL,
    texto_introducao TEXT NOT NULL,
    corpo_tecnico_json TEXT NOT NULL,
    numero_os VARCHAR(100) NULL,
    numero_apr VARCHAR(100) NULL,
    periodo_capa VARCHAR(100) NOT NULL,
    concessao VARCHAR(255) NOT NULL,
    hora_inicio VARCHAR(10) NOT NULL,
    hora_fim VARCHAR(10) NOT NULL,
    temperatura_inicio VARCHAR(20) NOT NULL,
    temperatura_fim VARCHAR(20) NOT NULL,
    frequencia_inicio VARCHAR(20) NOT NULL,
    frequencia_fim VARCHAR(20) NOT NULL,
    tensao_inicio VARCHAR(20) NOT NULL,
    tensao_fim VARCHAR(20) NOT NULL,
    nome_arquivo_original VARCHAR(255) NOT NULL,
    nome_arquivo_armazenado VARCHAR(255) NOT NULL,
    caminho_arquivo VARCHAR(500) NOT NULL,
    tamanho_bytes BIGINT NOT NULL,
    quantidade_fotos INT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEBIDO',
    erro_processamento TEXT NULL,
    id_usuario_envio INT NOT NULL,
    id_usuario_edicao INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_relatorio_manutencao),
    UNIQUE KEY uq_relatorio_manutencao_arquivo (nome_arquivo_armazenado),
    KEY ix_relatorio_manutencao_subestacao (id_subestacao),
    KEY ix_relatorio_manutencao_tipo_ativo (id_tipo_ativo),
    KEY ix_relatorio_manutencao_periodicidade (periodicidade),
    KEY ix_relatorio_manutencao_data_referencia (data_referencia),
    KEY ix_relatorio_manutencao_status (status),
    KEY ix_relatorio_manutencao_usuario (id_usuario_envio),
    KEY ix_relatorio_manutencao_usuario_edicao (id_usuario_edicao),
    CONSTRAINT fk_relatorio_manutencao_subestacao FOREIGN KEY (id_subestacao) REFERENCES subestacao (id_subestacao) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_relatorio_manutencao_tipo_ativo FOREIGN KEY (id_tipo_ativo) REFERENCES tipo_ativo (id_tipo_ativo) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_relatorio_manutencao_usuario FOREIGN KEY (id_usuario_envio) REFERENCES usuarios (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_relatorio_manutencao_usuario_edicao FOREIGN KEY (id_usuario_edicao) REFERENCES usuarios (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT ck_relatorio_manutencao_periodicidade CHECK (periodicidade IN ('SEMANAL', 'MENSAL', 'BIMESTRAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', '3_ANOS', '5_ANOS', '6_ANOS')),
    CONSTRAINT ck_relatorio_manutencao_status CHECK (status IN ('RECEBIDO', 'PROCESSANDO', 'CONCLUIDO', 'ERRO')),
    CONSTRAINT ck_relatorio_manutencao_tamanho CHECK (tamanho_bytes > 0),
    CONSTRAINT ck_relatorio_manutencao_fotos CHECK (quantidade_fotos > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE IF NOT EXISTS relatorio_manutencao_foto (
    id_relatorio_manutencao_foto INT NOT NULL AUTO_INCREMENT,
    id_relatorio_manutencao INT NOT NULL,
    id_ativo INT NULL,
    id_plano_item INT NULL,
    nome_arquivo_zip VARCHAR(500) NOT NULL,
    valor_medido VARCHAR(100) NULL,
    status_item VARCHAR(10) NOT NULL DEFAULT 'OK',
    observacao TEXT NULL,
    incluir BOOLEAN NOT NULL DEFAULT TRUE,
    confianca VARCHAR(20) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_relatorio_manutencao_foto),
    KEY ix_relatorio_foto_relatorio (id_relatorio_manutencao),
    KEY ix_relatorio_foto_ativo (id_ativo),
    KEY ix_relatorio_foto_item (id_plano_item),
    CONSTRAINT fk_relatorio_foto_relatorio FOREIGN KEY (id_relatorio_manutencao) REFERENCES relatorio_manutencao (id_relatorio_manutencao) ON DELETE CASCADE,
    CONSTRAINT fk_relatorio_foto_ativo FOREIGN KEY (id_ativo) REFERENCES ativo (id_ativo) ON DELETE SET NULL,
    CONSTRAINT fk_relatorio_foto_item FOREIGN KEY (id_plano_item) REFERENCES plano_item (id_plano_item) ON DELETE SET NULL,
    CONSTRAINT ck_relatorio_foto_status CHECK (status_item IN ('OK', 'NOK', 'NA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;


